language: node_js
node_js:
  - "4.1.1"

before_install:
- env
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- jspm install
script:
- gulp build
cache:
  directories:
  - node_modules
  - jspm_packages
notifications:
  email:
  - thomas.van.cleemput@gmail.com

addons:
  code_climate:
    repo_token: 27fefdd920bc01066288a69e24469db3c9b33ef397a99f819622bc96aea604b7

after_script:
  - cat coverage/report-lcov/lcov.info | node_modules/.bin/codeclimate
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: blog-tvc