language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - bower install
  - gulp build
  - gulp style
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: blog-tvc